---
id: rubykaigi-2015
base_name: the-history-of-testing-framework-in-ruby
tags:
- rabbit
- ruby
- testing-framework
presentation_date: 2015-12-12
version: 2015.12.12.4
licenses:
- CC BY-SA 4.0
slideshare_id: rubykaigi-2015
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
